### ISSUE TITLE
Placing an Angular project

### ISSUE THREAD

**Issue by NestorNjrzGical** [Narvalex/AES#2]
Angular is placed as one more option to consume the APIs that the BackEnd will expose

**Comment by Narvalex** [comment]
Thanks @NestorNjrzGical for the proposal. How do you plan to host the app? Ideally it would be hosted for free in Azure as an static web app. Maybe you could have a look here:
[Free Code Camp Angular in Azure as a SWA](https://www.freecodecamp.org/news/how-to-use-azure-static-web-apps-to-deploy-angular-app/)

**Comment by NestorNjrzGical** [comment]
Ok, I'm going to look at that documentation, and based on that I make a pull request. There, you will tell me what you think.

**Comment by Narvalex** [comment]
Angular was discarded in favor of Blazor for this .NET centric solution
